version: '2'
services:    
  app:
    container_name: matchups_web
    image: matchups
    env_file: matchups.env
    build: 
      context: . 
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"  
    volumes:
      - './:/app'  
  postgres:
    image: postgres:14.5
    container_name: matchups_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes: 
      - ./docker/db/data:/var/lib/postgresql/data
       # This copies the sql script to create tables
      - ./docker/db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql