version: '2'
services:
  matchups:
    build: .
    #command: npm run dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://admin@postgres/todos
  postgres:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: nba